nm = input()
pr = int(input())
wh = int(input())
mn = int(input())

print("Чек")
print(nm, '-', str(wh) + 'кг', '-', str(pr) + 'руб/кг')
print('Итого:', str(pr * wh) + 'руб')
print('Внесено:', str(mn) + 'руб')
print('Сдача:', str(mn - pr * wh) + 'руб')
